# fly.toml app configuration file generated for jedisteste on 2023-05-16T09:50:13-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jedisapp"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "gru"
processes = []

[build]

[deploy]
  release_command = "bundle exec rails db:migrate"

[env]
  LOG_LEVEL = "debug"
  RAILS_ENV = "production"

[experimental]
  auto_rollback = true

[[services]]
  grace_period = "30s"
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
