development:
  adapter: postgresql
  encoding: unicode
  host: db
  database: jedisapp_development
  pool: 5
  username: postgres
  password: 123

test:
  adapter: postgresql
  encoding: unicode
  host: db
  database: jedisapp_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: jedisapp_production
  pool: 5
  username: postgres
  password: