development:
  adapter: postgresql
  encoding: unicode
  database: jedisapp_development
  pool: 5
  username: pedronaves
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: jedisapp_test
  pool: 5
  username: pedronaves
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: jedisapp_production
  pool: 5
  username: pedronaves
  password: